services:
  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"

  next:
    build:
      context: next
    container_name: next
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - redis